---
bibliography: input/bib/ocs-paper.bib
---

# Introduction

Social cohesion has emerged as a critical dimension of societal well-being and democratic stability, particularly in regions experiencing rapid social and political transformation. In the case of the latinamerican region, recent years have been characterized by episodes of political instability, persistent inequalities and low economic growth, as well as cycles of social conflict [@undp_trapped_2023; @salazar-xirinachs_repensar_2023]. Social tensions therefore appear to have increased in the region, something that has been accompanied by a lack of trust in democratic institutions and widespread discontent with corruption and inequality. In such context, social cohesion has climbed the public and academic agendas, with recent diagnoses from both international organizations and national governments warning about its strains and the challenges it poses for democratic governance and inclusive development [@undp_trapped_2023; @salazar-xirinachs_repensar_2023; @castillo_cohesion_2022; @mideso_informe_2020].

Research in social cohesion tells us that it is a multidimensional phenomenon that encompasses various aspects of social life, including social relationships, shared values, and a sense of belonging to a community [@langer_conceptualising_2016; @delhey_happier_2016; @delhey_social_2018; @dragolov_social_2013; @janmaat_social_2010]. It is often conceptualized as a process that fosters social integration and solidarity among members of a society, contributing to social stability and the well-being of individuals. Social cohesion is also closely linked to the functioning of democratic institutions, as it can enhance trust in government and promote civic engagement. Furthermore, there are a series of contextual factors that has been associated with social cohesion, such as economic development, social inequality, and the quality of governance [@delhey_happier_2016; @delhey_social_2018; @janmaat_social_2010]. These factors can either strengthen or weaken social cohesion, depending on their specific characteristics and the context in which they operate. For instance, high levels of economic inequality have been found to undermine social cohesion by fostering feelings of injustice and social exclusion, while effective governance can enhance social cohesion by promoting trust and cooperation among citizens.

Despite its relevance and widespread use in public discussion, defining social cohesion theoretically and operationally remains a challenge. The literature ranges from studies focused on one or several specific dimensions of social cohesion [@ariely_does_2013; @castillo_cohesion_2022; @castillo_social_2023] to efforts to synthesize the phenomenon into comprehensive indices [@langer_conceptualising_2016; @delhey_happier_2016; @delhey_social_2018; @dragolov_social_2013; @janmaat_social_2010]. Such conceptual and methodological heterogeneity makes it difficult to compare countries and to detect transformations over time. Moreover, most of these definitions and their correspondent operationalizations have been tested mainly in European or high-income countries [@ariely_does_2013; @delhey_happier_2016], with only partial references to Latin America [@janmaat_social_2010]. This limitation persists even though evidence suggests that national and regional differences in cultural, historical, and institutional contexts shape the cohesion of societies and the factors that determine it [@janmaat_social_2010; @delhey_happier_2016]. Thus, despite the widespread perception that social cohesion is under strain in Latin American societies,there is a lack of empirical evidence of differences between countries, trends over time, and the factors that explain these changes.

The main aim of this paper is to analyze the evolution of social cohesion in Latin America over the past two decades. Building on the extant literature, we argue that individual structural factors such as education, income, and employment status, as well as contextual factors such as economic development, social inequality, and the quality of governance, are key determinants of social cohesion in the region. In order to reach this aim, we first need a validated measurement model of social cohesion that allows us to compare countries and detect changes over time. For this, we take the conceptual perspective proposed by Chan et al.[@chan_reconsidering_2006], which distinguishes between two main dimension of social cohesion: a horizontal one, which refers to the relationships between individuals and groups in a society, and a vertical one, which refers to the relationship between individuals and the state. We then operationalize these dimensions using data from the Latin American Public Opinion Project (LAPOP) AmericasBarometer, which provides a rich source of information on social attitudes and behaviors across the region. We use confirmatory factor analysis to validate our measurement model of social cohesion and to estimate the trajectories of social cohesion in Latin America over the last two decades. This approach will provide robust evidence on the changes in social cohesion in Latin America over the last two decades, contributing to the academic and policy discussion on the challenges and opportunities of social cohesion in the region. 


