---
bibliography: "input/bib/ocs-paper.bib"
csl: "input/bib/apa.csl"
---

# What is social cohesion?

Social cohesion is a multifaceted construct that plays a critical role in community interactions, impacting various social and health outcomes. The conceptualization of social cohesion encompasses various dimensions, such as connectedness, shared values, and participation in collective activities. Although its theoretical roots date back to the origins of social theory — and it has widespread use in public discourse — defining social cohesion remains a difficult task [@chan_reconsidering_2006]. Situated at the intersection of theoretical and descriptive approaches that emphasize cooperation and integration, as well as normative considerations about how societies stay united in the face of crises, tensions, and transformations, social cohesion has been defined in multiple ways, reflecting diverse perspectives, scopes, and indicators [@chan_reconsidering_2006; @castillo_conceptos_2021].

Social cohesion has been associated to different outcomes. Scholars as @turchi_intervening_2023 articulate that social cohesion becomes paramount in emergency contexts, where interpersonal connections can provide essential support and resilience. This assertion is supported by Stafford et al., who reveal that diminished social cohesion is correlated with health detriments, including increased mortality rates and adverse mental health indicators [@stafford_measuring_2003]. @le_displacement_2013 et al. further corroborate this perspective, exploring how cohesive communities can mitigate mental health issues in the aftermath of traumatic events. Moreover, context plays a significant role in the assessment and impacts of social cohesion. @nazmi_crosssectional_2010 illustrate how neighborhood characteristics influence health outcomes, suggesting that communities with stronger social interactions and solidarity can buffer against health stresses (Nazmi et al., 2010). In contrast, other research has shown that lower levels of perceived neighborhood cohesion are associated with adverse health conditions (Neergheen et al., 2019).

Most definitions of social cohesion share some common elements [@castillo_conceptos_2021]:

-   It is an attribute of the collective, not of individuals.
-   It is a multidimensional construct
-   It is a quality of social relations that enables the achievement of shared goals.
-   Given that subjects have a common objective, they are capable of cooperating to achieve these objectives.

Therefore, a robust definition of social cohesion should be able to take the previous elements into consideration, and at the same time it should allow for a comprehensive operationalization and measurement. Taking this into consideration, in this article we will begin with the definition proposed by Chan, To and Chan [-@chan_reconsidering_2006, p.90], for whom social cohesion "is a state of affairs concerning both the vertical and the horizontal interactions among members of society as characterized by a set of attitudes and norms that includes trust, a sense of belonging and the willingness to participate and help, as well as their behavioural manifestations".  From this definition, two main dimensions emerge. First, social cohesion has **a horizontal dimension**. By this we refer to the daily interactions among members of society. It contains subjective aspects (such as sense of belonging and interpersonal trust), as well as objective aspects, such as social networks and material conditions that facilitate or hinder these interactions. Second, social cohesion has **a vertical dimension**, which refers to the relations between individuals and social and political institutions. This dimension includes aspects such as trust in institutions, the legitimacy of the political system, and civic participation.

**Measuring Social Cohesion**

The measurement of social cohesion is equally critical and can vary considerably depending on the metrics employed. Bottoni emphasizes this by asserting that social cohesion is inherently multidimensional, incorporating structural components such as trust and social networks (Bottoni, 2016). Mair et al. and Cooper et al. both utilized factor analysis in their work to develop robust scales that effectively capture different facets of social cohesion, indicating the complex nature of social bonds within communities (Mair et al., 2009; Cooper et al., 2014). These scales assess variables like mutual responsibility and shared values, which are essential for understanding neighborhood dynamics.

A notable contribution to the framework of social cohesion measurement is provided by @delhey_social_2023, whose work emphasizes the necessity of incorporating a broad spectrum of attributes beyond mere trust and conflict perceptions. In their review, @delhey_social_2023 critique many existing measures for focusing narrowly on isolated components of social cohesion, which may lead to oversimplified interpretations. By highlighting social cohesion as a community asset that fosters solidarity and reduces conflict, Delhey et al. articulate its role in enhancing collective welfare and health outcomes. Moreover, their advocacy for multidimensional measurement approaches reflects an understanding that the impacts of social cohesion can vary significantly across different socio-cultural contexts. This adaptation is crucial for ensuring that social cohesion measures remain relevant and effective, addressing the criticisms of traditional models that fail to encompass the complexity of cohesive interactions.

# Studying social cohesion

Social Cohesion is usually understood as a *gradual* phenomenon, meaning that societies can display higher or lower levels of cohesion [@delhey_social_2023; @schiefer_essentials_2017]. This can be interpreted both longitudinally, that is, countries can increase or decrease their cohesion levels over time; as well as comparatively, that is, some countries can show higher levels of cohesion than others.

Despite the assumption that social cohesion levels change over time, the difficulty of conducting repeated measurements on population attitudes and behaviors hinders the longitudinal analysis of social cohesion. An important exception to this trend is the **Mapping Social Cohesion** Survey, conducted by the Scanlon Foundation Research Institute since 2007, which enables the construction of the Scanlon-Monash Index (SMI) of Social Cohesion. Thus, the SMI allows observing synthetically the evolution of Social Cohesion in Australia, recording a 22% decline since 2007 and significant decreases in 4 of its 5 dimensions [@odonnell_mapping_2024]. Another notable example of time comparison is the  **Social Cohesion Radar**, whose index can be reconstructed for four time periods between 1989 and 2012 [@delhey_social_2023]. However, its scope is limited to European and Western societies.

The literature on social cohesion appears to be more focused on establishing which countries show higher or lower levels of cohesion [@delhey_happier_2016; @delhey_social_2018], proving the existence of *cohesion regimes* [@janmaat_social_2010; @delhey_happier_2016], and determining the factors related to social cohesion [@delhey_happier_2016; @janmaat_social_2010; @delhey_social_2018; @green_social_2011]. These associated factors can be grouped into economic factors, political factors, and demographic factors.

Economic prosperity, often measured through GDP per capita, has been associated with higher levels of social cohesion. This association has been found across diverse cultural contexts [@janmaat_social_2010; @delhey_social_2023], although it appears to attenuate in some high-income Asian societies [@delhey_social_2018]. These findings align with universalist or modernist perspectives on social cohesion, which view cohesion as a phenomenon closely related to different stages of socioeconomic development [@janmaat_social_2010]. From these findings, we derive the first hypothesis of this article:

> H1: Countries with higher economic development will exhibit greater levels of social cohesion

Conversely, economic inequality has generally been associated with lower levels of social cohesion [@delhey_social_2018; @janmaat_social_2010; @delhey_social_2023]. Again, however, this association is attenuated in Asian societies, where moderate levels of inequality are associated with higher levels of cohesion [@janmaat_social_2010; @delhey_social_2018].

To date, there is no evidence regarding how inequality levels in Latin America relate to social cohesion. On one hand, despite being considered one of the world's most unequal regions, Latin Americans display exceptionally high expectations of social mobility [@somma_paradojas_2015], possibly due to increased educational coverage in many regional countries or the predominance of meritocratic justifications for educational and economic inequality [@somma_paradojas_2015; @castillo_socialization_2024]. Nevertheless, demands for greater equality, redistribution, and fair treatment [@cabib_nuestras_2025; @araujo_primer_2022], which have translated into mass protests in several regional countries, suggest that economic inequality is a relevant factor for social cohesion in Latin America. Therefore, we propose the following hypotheses:

> H2(a): Increases in a country's economic inequality will be associated with lower levels of social cohesion

> H2(b): Countries with higher levels of inequality will exhibit lower levels of social cohesion

The state's capacity to respond effectively to population challenges, particularly for vulnerable groups, has been identified as one of the primary sources of social cohesion in diverse societies [@kustov_diversity_2024; @njozela_measuring_2016; @andrews_welfare_2015]. In this vein, effective governance and robust institutions are typically associated with higher levels of social cohesion in contexts as diverse as Asia, Latin America, and Europe [@delhey_social_2018; @green_social_2011]. In contrast, the relationship between political systems and democratic regimes with social cohesion appears to be more context-dependent. While in wealthy Western societies liberal democracy tends to reinforce social cohesion levels, in some Asian countries authoritarian regimes have been linked to equally high levels of cohesion [@delhey_social_2018].

In Latin America, states are typically characterized by lower levels of efficiency and higher corruption indices, accompanied by citizenries with low levels of trust in political institutions and lower participation compared to the developed world. However, this institutional distrust coexists with a strong sense of national identification, even more pronounced than in the developed world [@somma_paradojas_2015]. For Somma [-@somma_paradojas_2015], this apparent paradox relates to the propensity of Latin American societies toward personalist and populist leadership. In this context, consistent with what Guillermo O'Donnell described as delegative democracies [@toppi_guillermo_2018], broad sectors of the citizenry appear willing to trade liberal democratic principles in favor of authoritarian leadership when they perceive that democratic institutions fail to resolve their daily problems. This suggests that governance effectiveness—rather than political regime type—is the institutional factor that carries greater weight on social cohesion levels in Latin American societies. From this discussion, we propose the following hypotheses:

> H4(a): Increases in a country's governance levels will be associated with higher levels of social cohesion

> H4(b): Countries with higher levels of governance will exhibit higher levels of social cohesion

Cultural and demographic variables, including ethnic, religious, and national identities, have demonstrated complex effects on social cohesion levels, varying substantially by context. This contextual character is particularly evident in the impact of ethnic diversity on social cohesion. On one hand, several studies have identified negative effects of ethnic diversity on indicators such as sense of belonging or the strength of neighborhood networks [@gijsberts_hunkering_2011; @ariely_does_2013], an association that is particularly pronounced in contexts of high racial segregation, such as the United States [@meer_ethnic_2014]. Nevertheless, other research has shown that institutional factors and the implementation of inclusive policies can moderate, or even reverse, this relationship [@meer_ethnic_2014; @kustov_diversity_2024; @delhey_social_2018; @reeskens_nationalism_2012; @delhey_social_2023].

The management of ethnic diversity in Europe and North America contrasts significantly with the Latin American reality, characterized by greater ethnic and linguistic heterogeneity. Despite episodes of conflict arising from relationships between states and indigenous peoples, Latin American countries have demonstrated strong national identities [@somma_paradojas_2015]. However, recent changes in migration patterns, which have favored intraregional migration in both relative and absolute terms [@stefoni_panorama_2018], could constitute new sources of tension for social cohesion in Latin American societies. Although Latin Americans tend to display levels of ethnic-religious and national tolerance higher than those observed in several European countries [@somma_paradojas_2015], cases such as Chile—in response to massive Venezuelan migration—evidence signs of deterioration in relations between migrants and non-migrants in recent years [@castillo_social_2023]. In light of this, we propose the following hypotheses:

> H5(a): Increases in the proportion of migrant population in a country will be associated with decreases in social cohesion levels

> H5(b): Countries with higher levels of ethnic diversity will exhibit lower levels of social cohesion

> H5(c): The impact of migration on social cohesion will be smaller in countries with better governance levels
