# Introducción

En América Latina, los últimos años han estado marcadas por episodios de inestabilidad política, desigualdades persistentes y bajo crecimiento económico, y ciclos de conflictividad social [@undp_trapped_2023; @salazar-xirinachs_repensar_2023] . De tal modo, las tensiones sociales parecen haber aumentado en la región, reflejando una falta de confianza en las instituciones democráticas y un descontento generalizado con la corrupción y la desigualdad. En este contexto, la cohesión social ha escalado en la agenda pública y académica, con diagnósticos recientes tanto de organismos internacionales como de gobiernos nacionales que advierten sobre sus tensiones y desafíos para la gobernabilidad democrática y el desarrollo inclusivo [@undp_trapped_2023; @salazar-xirinachs_repensar_2023; @castillo_cohesion_2022; @mideso_informe_2020].

Sin embargo, pese a su uso generalizado y cotidiano en la discusión pública, definir cohesión social teórica y operacionalmente sigue siendo un desafío. La literatura oscila entre estudios focalizados en a una o varias dimensiones específicas de la cohesión social [@ariely_does_2013; @castillo_cohesion_2022; @castillo_social_2023] a esfuerzos por sintetizar el fenómeno en índices comprehensivos [@langer_conceptualising_2016; @delhey_happier_2016; @delhey_social_2018; @dragolov_social_2013; @janmaat_social_2010]. Esta heterogeneidad conceptual y metodológica dificulta la comparación entre países, así como la detección de transformaciones a lo largo del tiempo.

Por lo demás, la mayoría de estas definiciones se han puesto a prueba principalmente en países europeos o de altos ingresos [@ariely_does_2013; @delhey_happier_2016], con solo menciones parciales a América Latina [@janmaat_social_2010]. Esta limitación se mantiene pese a que la evidencia apunta a que las diferencias nacionales y regionales en los contextos culturales, históricos e institucionales moldean la cohesión de las sociedades y los factores que la determinan [@janmaat_social_2010; @delhey_happier_2016]. De tal modo, pese a la percepción generalizada de que la cohesión social es un fenómeno en tensión en las sociedades latinoamericanas, existe evidencia empírica de las diferencias entre países, las tendencias en el tiempo y los factores que explican estos cambios.

Este artículo busca cubrir esas brechas proponiendo y validando un modelo de medición que permita un análisis comparativo, longitudinal y multinivel de la cohesión social en América Latina. En concreto, buscamos avanzar en: (i) una operacionalización clara y validada que integre dimensiones claves a partir de la literatura existente y los datos disponibles para la región; (ii) la estimación de trayectorias regionales y nacionales durante las últimas dos décadas; y (iii) la identificación de factores asociados a estos cambios mediante la aplicación de modelos de regresión multinivel. Con esto, se espera aportar evidencia robusta sobre los cambios en la región en las últimas dos décadas, aportando a la discusión académica y política sobre los desafíos y oportunidades de la cohesión social en América Latina.
