# ¿Qué es la cohesión social?

Aunque sus raíces teóricas se remontan a los inicios de la teoría social -- y su uso extendido en la discusión pública - definir cohesión social sigue siendo una tarea difícil [@chan_reconsidering_2006]. Situada en la intersección entre enfoques teóricos y descriptivos que enfatizan las cooperación y la integración, y consideraciones normativas acerca de cómo la sociedades se mantienen unidad ante crisis, tensiones y transformaciones, la cohesión social se ha definido de múltiples maneras, reflejando diversas perspectivas, alcances e indicadores [@chan_reconsidering_2006; @castillo_conceptos_2021].

Con todo, la mayoría de las definiciones comparten algunos elementos en común [@castillo_conceptos_2021]:

-   Es un atributo del colectivo, no de los individuos.
-   Es un constructo multidimensional
-   Es una cualidad de las relaciones sociales que permite alcanzar fines compartidos.
-   Dado que los sujetos tiene un objetivo común, son capaces cooperar para lograr estos objetivos.

Una definición robusta de cohesión social debe integrar estos elementos. A la vez, debe ser una definición mínima e intuitiva, que permita su operacionalización y medición, así como la comparación en contextos diversos y posibilite la discusión e espacios públicos [@chan_reconsidering_2006].

De tal modo, en este artículo partiremos de la definición propuesta por Chan, To y Chan [-@chan_reconsidering_2006, p.90], para quienes la cohesión social

> is a state of aﬀairs concerning both the vertical and the horizontal interactions among members of society as characterized by a set of attitudes and norms that includes trust, a sense of belonging and the willingness to participate and help, as well as their behavioural manifestations.

De la definición, pues, se desprenden dos dimensiones principales. En primer lugar, la cohesión social tiene **una dimensión horizontal**. Con esto nos referimos a las interacciones cotidianas entre los miembros de una sociedad. Contiene aspectos subjetivos (tales como el sentido de pertenencia y la confianza interpersonal), como aspecto objetivos, como las redes sociales y las condiciones materiales que facilitan o dificultan estas interacciones.

En segundo lugar, la cohesión social tiene **una dimensión vertical**, que se refiere a las relaciones entre los individuos y las instituciones sociales y políticas. Esta dimensión incluye aspectos como la confianza en las instituciones, la legitimidad del sistema político y la participación cívica.

# Tendencias y factores relacionados a la Cohesión Social

Diversos estudios muestran que las trayectorias de la cohesión social difieren ampliamente entre países. Entre los factores que influyen en estas trayectorias se cuentan el crecimiento y la desigualdad económica, la configuración de los sistemas de bienestar, la composición cultural y étnica, y los legados autoritatorios. La intensidad y la dirección de sus efectos, sin embargo, dependen en gran medida del contexto. Por ejemplo, mientras en Europa el crecimiento económico, la igualdad social y las democracias liberales suelen asociarse con mayores niveles de cohesión, en varios países de Asia se observan niveles comparables en contextos de desigualdad moderada y regímenes autoritarios. Ahora bien, en todos estos estudios las menciones a determinantes de la cohesión social en sociedades latinoamericanas son escasas.

Con todo, es posible agrupar los factores identificados en tres dimensiones:

1.  Factores socioeconómicos
2.  Factores institucionales
3.  Factores culturales

A continuación se revisan cada una de ellas.

## 1) Factores socioeconómicos

La prosperidad económica, a menudo medida a través del PIB per cápita, se ha asociado con mayores niveles de cohesión social. Esta asociación se ha encontrando en diversos contextos culturales [@janmaat_social_2010; @delhey_social_2023], aunque parece atenuarse en algunas sociedades asiáticas de altos ingresos [@delhey_social_2018]. Estos hallazgos van en línea con las perspectivas universalistas o modernistas de la cohesión social, para quienes la cohesión es un fenómeno estrechamente relacionado con distintas etapas del desarrollo socioeconómico [@janmaat_social_2010]. De estos hallazgos, se desprende la primera hipótesis del artículo:

> H1(a): Aumentos en el desarrollo económico de un país estarán asociados con incrementos en los niveles de cohesión social

> H1(b): Los países con un mayor desarrollo económico presentarán mayores niveles de cohesión social

Por otro lado, la desigualdad económica se ha asociado generalmente con menores niveles de cohesión social [@delhey_social_2018; @janmaat_social_2010]. Nuevamente, sin embargo, la asociación se atenúa en sociedades asiáticas, donde niveles medios de desigualdad están asociados con mayores niveles de cohesión [@janmaat_social_2010; @delhey_social_2018].

No hay evidencia sobre como los niveles de desigualdad en América Latina se relacionan con la cohesión social. Por un lado, pese a ser considerada una de las regiones más desiguales del mundo, los latinoamericanos muestran altísimas expectativas de movilidad social [@somma_paradojas_2015], posiblemente debido de al aumento de la cobertura educativa en muchos países de la región o al predominio de las justificaciones meritocráticas para la desigualdad educativa y económica[@somma_paradojas_2015; @castillo_socialization_2024]. Con todo, las demandas de mayor igualdad, redistribución y trato justo [@cabib_nuestras_2025; @araujo_primer_2022], que se han traducido en protestas masivas en varios países de la región, sugieren que la desigualdad económica es un factor relevante para la cohesión social en América Latina. Por lo tanto, planteamos las siguientes hipótesis:

> H2(a): Aumentos en la desigualdad económica de un país estarán asociados con menores niveles de cohesión social

> H2(b): Países con mayores niveles de desigualdad presentarán menores niveles de cohesión social

> H3(a): Individuos con mayor nivel educativo mostrarán mayores nivel de cohesión social

> H3(b): El efecto de la desigualdad económica sobre la cohesión social será menor en países con mayores oportunidades educativas.


## 2) Factores institucionales

La capacidad del Estado para responder de manera efectiva a las problemáticas de la población, especialmente de los grupos más vulnerables, ha sido identificada como una de las principales fuentes de cohesión social en diversas sociedades [@kustov_diversity_2024; @njozela_measuring_2016; @andrews_welfare_2015]. En esta línea, una gobernanza eficaz y la presencia de instituciones sólidas suelen asociarse con mayores niveles de cohesión soical en contextos tan diversos como Asia, América Latina y Europa [@delhey_social_2018; @green_social_2011].

En contraste, la relación entre los sistemas políticos y el régimen democrático con la cohesión social parece ser más dependiente del contexto. Mientras que en sociedades occidentales de altos ingresos la democracia liberal tiende a reforzar los niveles de cohesión social, en algunos países asiáticos los regímenes autoritarios se han viculado con niveles igualmente elevados de cohesión [@delhey_social_2018]

En América Latina, los Estados suelen caracterizarse por menores niveles de eficiencia y mayores índices de corrupción, acompañados de una ciudadnaía que presenta bajos niveles de confianza en las instituciones políticas y una menor participación en comparación con el mundo desarrollado. Sin embargo, esta desconfianza institucional convive con un fuerte sentido de identificación nacional, incluso más pronunciado que en el primer mundo [@somma_paradojas_2015]. Para Somma [-@somma_paradojas_2015], esta aparente paradoja se relaciona con la propensión de las sociedades latinoamericanas hacia liderazgos personalistas y populistas. En este contexto, en línea con lo que Guillermo O'Donnell describió como democracias delegativas [@toppi_guillermo_2018], amplios sectores de la ciudadanía estarían dispuestos a transar principios de la democracia liberal en favor a liderazgos autoritarios cuando perciben que las instituciones democráticas no logran resolver sus problemas cotidianos. Esto sugiere que la efectividad de la gobernanza -- más que el tipo de régimen político -- es el factor institucional que ejerce un mayor peso en los niveles de cohesión social en las sociedades latinoamericanas. A partir de esta discusión, planteamos las siguientes hipótesis:

> H4(a): Aumentos en los niveles de gobernanza en un país estarán asociados con mayores niveles de cohesión social

> H4(b): Países con mayores niveles de gobernanza presentarán mayores niveles de cohesión social

## 3) Factores culturales

Las variables culturales y demográficas, incluidas las identidades étnicas, religiosas y nacionales, han mostrado efectos complejos sobre niveles de cohesión social, variando sustancialmente según el contexto. Este carácter contextual es especialmente evidente en el impacto de la diversidad étnica sobre la cohesión social.

Por un lado, diversos estudios han identificados esfectos negativos de la diversidad étnica sobre indicadores como el sentido de pertenencia o la fortaleza de las redes vecinales[@gijsberts_hunkering_2011; @ariely_does_2013], asociación que resulta particularmente marcada en contexto de alta segregación racial, como el de los Estados Unidos [@meer_ethnic_2014]. No obstante, otros trabajos han mostrado que factores institucionales y la implementación de políticas inclusivas pueden moderar, o incluso invertir, esta relación [@meer_ethnic_2014; @kustov_diversity_2024; @delhey_social_2018; @reeskens_nationalism_2012].

La gestión de la diversidad étnica en Europa y América del Norte constrasta de manera importante con la realidad latinoamericana, caracterizada por una mayor heterogeneidad étnica y lingüistica. Pese a episodios de conflictividad derivados de las relacioens entre los Estados y los pueblos indígenas, los países latinoamericanos han demostrados fuertes identidades nacionales [@somma_paradojas_2015].

Sin embargo, los cambios recientes en los patrones migratorios, que han favorecido la migración intrarregional tanto en términos relativos como absolutos [@stefoni_panorama_2018], podrían constituir nuevas fuentes de tensión para la cohesión social en las sociedades latinoamericanas. Aunque los latinoamericanos tienden a mostrar niveles de tolerancia étnico-religiosa y nacional superiores a los observados en varios países europeos [@somma_paradojas_2015], casos como el chileno —frente a la migración masiva de población venezolana— evidencian signos de deterioro en las relaciones entre migrantes y no migrantes durante los últimos años [@castillo_social_2023]. Frente a esto, proponemos las siguientes hipótesis:

> H5(a): Aumentos en la proporción de población migrante en un país estarán asociados a disminuciones en los niveles de cohesión social

> H5(b): El impacto de la migración sobre la cohesión social será menor en países con mejores niveles de gobernanza

<!-- El efecto de la religiosidad sobre la cohesión social también ha sido objeto de estudio. Una mayor religiosidad y heterogeneidad religiosa puede estar asociada a mayores niveles de confianza interpersonal y participación cívica [@schnabel_god_2014]. Estos hallazgos se centran principalmente en el contexto cultural europeo, y no se refieren a la realidad latinoamericana, donde el catolicisimo ha sido la religión predominante en la mayoría de los países del continente desde la colonización española y portuguesa. Sin embargo, debido al auge del pentecostalismo (como en Brasil o en los países centroamericanos) y al crecimiento de la población no religiosa (como en Argentina, Chile y Uruguay), la hegemonía católica en América Latina ha comenzado a debilitarse [@valenzuela_creen_2013]. Este cambio en el panorama religioso podría tener implicancias importantes para la cohesión social en la región, particularmente si como se ha observado en el caso chileno, el debilitamiento de las identidades religiosas tradicionales se ha asociado a procesos de individuación y de desafección institucional [@bravovega_religious_2024; @cortesparedes_autonomia_2022]. -->
