# Resultados

```{r}
#| echo: false

## cargar base

load("input/proc/datos-completos.rdata")
load("input/proc/micro-macro-merge.rdata")

datos_merge_b <- datos_merge_b |>
  mutate(across(where(haven::is.labelled), ~ vctrs::vec_data(.)),
         pais= as.factor(pais))

datos_merge_b$country_wave = do.call(paste, c(datos_merge_b[c("pais", "ola")], sep = "_"))

```

## Descriptivos

```{r}
#| label: fig-ch
#| fig-cap: Evolución dimensiones Cohesión Horizontal (2004-2022)


olas <- datos_merge_b |>
  group_by(ola) |>
  summarise(seguridad_prom = mean(seguridad_ind, na.rm=T),
            confianza_prom = mean(confianza_it_ind, na.rm=T)) |>
  pivot_longer(
    cols = c(confianza_prom, seguridad_prom),
    names_to = "indicador",
    values_to = "promedio"
  ) |>
  mutate(indicador = recode(indicador,
                            "confianza_prom" = "Confianza Interpersonal",
                            "seguridad_prom" = "Seguridad Pública"))
olas |>
  ggplot(aes(x = ola, y = promedio, color=indicador)) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(x = "Ola", y = "Promedio", color=NULL) +
  theme_minimal() + 
  theme(legend.position = "bottom")

```


```{r}
#| label: fig-cv
#| fig-cap: Evolución dimensiones Cohesión Vertical (2004-2022)

olas <- datos_merge_b |>
  group_by(ola) |>
  summarise(confianza_prom = mean(confianza_inst_ind, na.rm=T),
            democracia_prom = mean(democracia_ind, na.rm=T)) |>
  pivot_longer(
    cols = c(confianza_prom, democracia_prom),
    names_to = "indicador",
    values_to = "promedio"
  ) |>
  mutate(indicador = recode(indicador,
                            "confianza_prom" = "Confianza en las Instituciones",
                            "democracia_prom" = "Actitudes hacia la democracia"))
olas |>
  ggplot(aes(x = ola, y = promedio, color=indicador)) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(x = "Ola", y = "Promedio", color=NULL) +
  theme_minimal() + 
  theme(legend.position = "bottom")

```

```{r}
#| label: fig-correlación
#| fig-cap: "Correlación subdimensiones de la Cohesión Social"
#| results: asis


chart.Correlation(datos_wide %>%
                    na.omit() |>
                    select(c("Confianza Interpersonal",
                             "Seguridad Pública",
                             "Confianza en las Instituciones",
                             "Actitudes a la Democracia")))

```

## Análisis Factorial Confirmatorio

```{r}
#| label: afc
#| fig-cap: Análisis Factorial Confirmatorio Modelo de Medición de Cohesión Social

m1 <- 'ch =~ seguridad_ind + confianza_it_ind
       cv =~ confianza_inst_ind + democracia_ind'

m1_cfa <- cfa(
  m1, data = datos_merge_b, std.lv = TRUE)

semPaths(m1_cfa,
         what = "std",
        label.cex = 1, edge.label.cex = 1, # tamaño flechas y caracteres
        residuals = FALSE, # no mostrar residuos
        edge.color = "black") # color flechas

fit <- fitmeasures(m1_cfa, fit.measures = c("rmsea", "cfi", "chisq", "pvalue", "df"))

```
Nota. RMSEA = `r round(fit["rmsea"], 3)`, CFI = `r round(fit["cfi"], 3)`, Chi-cuadrado = `r round(fit["chisq"], 2)`, gl = `r fit["df"]`, p-valor = `r round(fit["pvalue"], 3)`.


```{r}
#| label: fig-cs
#| tab-cap: Evolución dimensiones Cohesión Social (2004-2022)

olas <- datos_merge_b |>
  group_by(ola) |>
  summarise(horizontal_prom = mean(`cohesion_horizontal_ind`, na.rm=T),
            vertical_prom = mean(`cohesion_vertical_ind`, na.rm=T),
            cohesion_prom = mean(`cohesion_general_ind`, na.rm=T)) |>
  pivot_longer(
    cols = c(horizontal_prom, vertical_prom, cohesion_prom),
    names_to = "indicador",
    values_to = "promedio"
  ) |>
  mutate(indicador = recode(indicador,
                            horizontal_prom = "Cohesión Horizontal",
                            vertical_prom = "Cohesión Vertical",
                            cohesion_prom = "Cohesión Social"))

olas |>
  ggplot(aes(x = ola, y = promedio, color=indicador)) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(x = "Ola", y = "Promedio", color=NULL) +
  theme_minimal() + 
  theme(legend.position = "bottom")

```

## Modelos Multinivel

```{r}
#| label: preparacion-datos

## Estandarizar continuos tras separar W/B (recomendado)
z <- function(x) as.numeric(scale(x))

datos_merge_b <- datos_merge_b %>%
  mutate(
    pib_we  = z(pib_we),   gini_we = z(gini_we), wgi_we = z(wgi_we), dem_we = z(dem_we),
    mig_we  = z(mig_we),   edu_we = z(edu_we),
    pib_be  = z(pib_be),   gini_be = z(gini_be), wgi_be = z(wgi_be), dem_be = z(dem_be),
    mig_be  = z(mig_be),   edu_be = z(edu_be),
    edad_c = scale(edad) %>% as.numeric()
  ) |>
  select(cohesion_general_ind, cohesion_vertical_ind, cohesion_horizontal_ind,
         nivel_educ, sexo, edad_c, ola, pos_politica,
         pib_we, gini_we, dem_we, wgi_we, mig_we, edu_we,
         pib_be, gini_be, dem_be, wgi_be, mig_be, edu_be,
         country_wave, pais, wt) |> na.omit()


```

```{r}
#| label: modelos-nulos

m0_ch = lmer(cohesion_horizontal_ind ~ 1 + (1 | country_wave) + (1 |pais), data=datos_merge_b, weights=wt)

icc(m0_ch, by_group=TRUE) # 2.3% y 5.6%

m0_cv = lmer(cohesion_vertical_ind ~ 1 + (1 | country_wave) + (1 |pais), data=datos_merge_b, weights=wt)

icc(m0_cv, by_group=TRUE) # 6.3% y 6.3%

m0_cs = lmer(cohesion_general_ind ~ 1 + (1 | country_wave) + (1 |pais), data=datos_merge_b, weights=wt)

icc(m0_cs, by_group=TRUE) # 4.9% y 7.5%
```


```{r}
#| label: tbl-modelos-horizontal
#| tbl-cap: Modelos para cohesión horizontal 
#| results: asis


# Modelo 1: Nivel individual
m1 <- lmer(cohesion_horizontal_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + (1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 2: Nivel Ola Pais
m2 <- lmer(cohesion_horizontal_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)


# Modelo 3: Nivel País
m3 <- lmer(cohesion_horizontal_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 4: Interacciones
m4 <- lmer(cohesion_horizontal_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

sjPlot::tab_model(m1, m2, m3, m4,
                  show.ci = FALSE,
                  dv.labels = c("m1", "m2", "m3", "m4"))

m5 <- lmer(cohesion_horizontal_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
  scale(ola):mig_be +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)


sjPlot::tab_model(m4, m5,
                  show.ci = FALSE,
                  dv.labels = c("m4", "m5"))

```


```{r}
#| eval: false

p_load(influence.ME)

estex.cw <- influence(m4, "country_wave")
estex.c <- influence(m4, "pais")

# Casos influyentes a nivel ola-país

cooks_cw <- cooks.distance(estex.cw, sort = T)
cut_cw <- 4/sqrt(130)

plot(estex.cw, which="cook",
     cutoff=cut_cw, sort=TRUE)

# Influyentes a nivel país

cut_c <- 4/sqrt(22)

plot(estex.c, which="cook",
     cutoff=cut_c, sort=TRUE)
```


```{r}
#| label: tbl-modelos-vertical
#| tbl-cap: Modelos para cohesión vertical
#| results: asis

# Modelo 1: Nivel individual
m1 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + (1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 2: Nivel scale(ola) Pais
m2 <- lmer(cohesion_vertical_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)


# Modelo 3: Nivel País
m3 <- lmer(cohesion_vertical_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 4: Interacciones
m4 <- lmer(cohesion_vertical_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

sjPlot::tab_model(m1, m2, m3, m4,
                  show.ci = FALSE,
                  dv.labels = c("m1", "m2", "m3", "m4"))

m5 <- lmer(cohesion_vertical_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
  scale(ola):wgi_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

sjPlot::tab_model(m4, m5,
                  show.ci = FALSE,
                  dv.labels = c("m4", "m5"))


```

```{r}
#| eval: false

estex.cw <- influence(m4, "country_wave")
estex.c <- influence(m4, "pais")

# Casos influyentes a nivel ola-país

cooks_cw <- cooks.distance(estex.cw, sort = T)
cut_cw <- 4/sqrt(130)

plot(estex.cw, which="cook",
     cutoff=cut_cw, sort=TRUE)

# Influyentes a nivel país

cut_c <- 4/sqrt(22)

plot(estex.c, which="cook",
     cutoff=cut_c, sort=TRUE)

# Uruguay y Bolivia aparecen como influyentes
```
```{r}
data_cut <- datos_merge_b |> filter(pais!="Uruguay" & pais!="Bolivia")

m5 <- lmer(cohesion_vertical_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
(1 | country_wave) + (1 | pais), data= data_cut, weights= wt)

sjPlot::tab_model(m4, m5,
                  show.ci = FALSE,
                  dv.labels = c("completo", "sin influyentes"))
```



```{r}
#| label: tbl-modelos-general
#| tbl-cap: Modelos para cohesión social
#| results: asis

# Modelo 1: Nivel individual
m1 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + (1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 2: Nivel scale(ola) Pais
m2 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 3: Nivel País
m3 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

# Modelo 4: Interacciones
m4 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

sjPlot::tab_model(m1, m2, m3, m4,
                  show.ci = FALSE,
                  dv.labels = c("m1", "m2", "m3", "m4"))

m5 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
  scale(ola):wgi_we +
(1 | country_wave) + (1 | pais), data= datos_merge_b, weights= wt)

sjPlot::tab_model(m4, m5,
                  show.ci = FALSE,
                  dv.labels = c("m4", "m5"))


```

```{r}
#| eval: false

# estex.cw <- influence(m4, "country_wave")

# 
# # Casos influyentes a nivel ola-país
# 
# cooks_cw <- cooks.distance(estex.cw, sort = T)
# cut_cw <- 4/sqrt(130)
# 
# plot(estex.cw, which="cook",
#      cutoff=cut_cw, sort=TRUE)

# Influyentes a nivel país

estex.c <- influence.ME::influence(m5, "pais")
cooks_c <- cooks.distance(estex.c, sort = T)
cut_c <- 4/sqrt(22)

plot(estex.c, which="cook",
     cutoff=cut_c, sort=TRUE)

# De nuevo Bolivia y Uruguay
```

```{r}

m6 <- lmer(cohesion_general_ind ~ 1 + factor(nivel_educ) + factor(sexo) + edad_c + I(edad_c^2) + factor(pos_politica) + scale(ola) + 
pib_we + gini_we + dem_we + wgi_we + mig_we + edu_we +
pib_be + gini_be + dem_be + wgi_be + mig_be + edu_be +
mig_we:wgi_be +
edu_be:gini_be +
  edu_be:gini_we +
  scale(ola):wgi_we +
  scale(ola):edu_we +
(1 | country_wave) + (1 | pais), data= data_cut, weights= wt)

sjPlot::tab_model(m5, m6,
                  show.ci = FALSE,
                  dv.labels = c("completo", "sin influyentes"))
```






